/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaproject02;

public class App {
    public static void main(String[] args) {
        @SuppressWarnings("unused")
        Game game = new Game();
    }
}
