/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaproject02;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

@SuppressWarnings("unused")
class AppTest {
    @Test void appHasAMenu() {
        Game classUnderTest = new Game();
        // assertNotNull(classUnderTest.menu, "app should have a greeting");
    }
}
